project:
  type: website
  output-dir: _site
  resources:
    - "netlify.toml"
  render:
    - "**.qmd"
    - "!v1/**"
    - "examples/**"
    - "!examples/_check/**"
    - "reference/**/**.md"

  # pre-render: spin-examples.R
  preview:
    port: 5555
    browser: false


execute:
  enabled: true
  eval: true
  freeze: auto



website:
  title: TensorFlow for R
  site-url: https://tensorflow.rstudio.com/
  repo-url: https://github.com/rstudio/tensorflow.rstudio.com
  google-analytics: "UA-20375833-3"
  repo-actions: [edit, source, issue]
  search: true
  page-navigation: true
  reader-mode: false
  favicon: "images/favicon/icon.png"
  page-footer:
    left: |
      Proudly supported by
      [![](/images/RStudio-Logo-flat.svg){fig-alt="RStudio" width=65px}](https://www.rstudio.com)
    right:
      - Copyright © 2015-2022 The TensorFlow Authors and RStudio, PBC.
  navbar:
    search: true
    logo: "images/favicon/icon.png"
    file: index.qmd
    left:
      - { text: Install, href: install/ }
      - { text: Tutorials, href: tutorials/ }
      - { text: Guides, href: guides/ }
      - { text: Examples, href: examples/ }
      - { text: Reference, href: reference/ }
    right:
      - icon: github
        aria-label: GitHub repository
        menu:
          - { text: tensorflow,  href: https://github.com/rstudio/tensorflow }
          - { text: keras,       href: https://github.com/rstudio/keras }
          - { text: tfdatasets,  href: https://github.com/rstudio/tfdatasets }
          - { text: tfautograph, href: https://github.com/t-kalinowski/tfautograph }
          - { text: website,     href: https://github.com/rstudio/tensorflow.rstudio.com }

  sidebar:
    - title: "Install"
      alignment: left
      collapse-level: 2
      style: "docked"
      contents:
        - install/index.qmd
        - install/custom.qmd
        - section: GPU
          href: install/gpu.qmd
          contents:
            - install/local_gpu.qmd
            - install/cloud_server_gpu.qmd

    - title: "Tutorials"
      contents:
        - tutorials/index.qmd
        - section: Quickstart
          contents:
            - tutorials/quickstart/beginner.qmd
            - tutorials/quickstart/advanced.qmd
        - section: "ML basics with Keras"
          contents:
            - tutorials/keras/classification.qmd
            - tutorials/keras/text_classification.qmd
            - tutorials/keras/regression.qmd
            - tutorials/keras/overfit_and_underfit.qmd
            - tutorials/keras/save_and_load.qmd
            - tutorials/keras/text_classification_with_hub.qmd

        # - section: "Data Loading basics with TF Datasets"
        #   contents:
        #     - tutorials/tfdatasets/csv.qmd

    - title: "Reference"
      contents:
        - section: R packages
          contents:
            - reference/tensorflow/index.qmd
            - reference/keras/index.qmd
            - reference/tfdatasets/index.qmd
            - reference/tfautograph/index.qmd
            - reference/tfhub/index.qmd
            - reference/tfruns/index.qmd
            - reference/cloudml/index.qmd
            - reference/tfhub/index.qmd
            - text: tfprobability
              href: "https://rstudio.github.io/tfprobability/index.html"


    - title: "Guides"
      contents:
        - guides/index.qmd

        - section: Tensorflow Basics
          contents:
            - { text: Overview, href: guides/tensorflow/basics.qmd }
            - { text: Tensors, href: guides/tensorflow/tensor.qmd }
            - { text: Variables, href: guides/tensorflow/variable.qmd }
            - { text: Automatic differentiation, href: guides/tensorflow/autodiff.qmd }
            - { text: Graphs and functions, href: guides/tensorflow/intro_to_graphs.qmd }

        - section: Keras
          contents:
            - guides/keras/basics.qmd
            - guides/keras/sequential_model.qmd
            - guides/keras/functional_api.qmd
            - guides/keras/training_with_built_in_methods.qmd
            - guides/keras/making_new_layers_and_models_via_subclassing.qmd
            - guides/keras/serialization_and_saving.qmd
            - guides/keras/preprocessing_layers.qmd
            - guides/keras/customizing_what_happens_in_fit.qmd
            - guides/keras/writing_a_training_loop_from_scratch.qmd
            - guides/keras/working_with_rnns.qmd
            - guides/keras/understanding_masking_and_padding.qmd
            - guides/keras/writing_your_own_callbacks.qmd
            - guides/keras/transfer_learning.qmd

        - section: TensorFlow in depth
          contents:
            - guides/tensorflow/tensor_slicing.qmd
            - { text: Autograph, href: guides/tfautograph/index.qmd }

        - section: Data input pipelines
          contents:
            - guides/tfdatasets/index.qmd

        - section: Track Experiments
          contents:
            - guides/tfruns/index.qmd
            - guides/tfruns/managing.qmd
            - guides/tfruns/tuning.qmd
            - guides/tensorboard/index.qmd

        - section: Deployment
          href: guides/deploy/index.qmd
          contents:
            - guides/deploy/plumber.qmd
            - guides/deploy/shiny.qmd
            - guides/deploy/docker.qmd
            - guides/deploy/rsconnect.qmd


format:
  html:
    df-print: tibble
    toc: true
    code-overflow: wrap
    mainfont: Lato
    theme:
      light: [flatly, _css/light.scss, _css/custom.scss]
      dark: [darkly, _css/dark.scss, _css/custom.scss]
